---
title: "QB6 Measures"
---

```{r setup, include=FALSE}
library(rmarkdown)


# the package "xaringanExtra" is needed to set up panels. Download here: devtools::install_github("gadenbuie/xaringanExtra")
library(xaringanExtra)

xaringanExtra::use_panelset()
knitr::opts_chunk$set(echo = F, warning = FALSE, message = FALSE)

```

### Acknowledgments {.appendix}

This website was made by [Gayoung Son](mailto:g.son@unibas.ch) with the [distill package](https://rstudio.github.io/distill/) and a custom theme by Alison Hill & [Desirée De Leon](https://desiree.rbind.io/).

# QUESTIONNAIRE BIG SIX (QB6) MEASURES
Big Six inventories of varying length were tested for comparative validity along with the BFI, the NEO-FFI, the HEXACO, and the IPIP measures in Thalmayer, Saucier, and Eigenhuis (2011; Psychological Assessment). The cross-cultural 30-QB6 includes the items that functioned the most consistently across 26 cultural settings (Thalmayer & Saucier, 2014).

## 30QB6 (A VARIANT OF THE 36QB6 CONSISTING OF BEST-PERFORMING ITEMS IN CROSS-NATIONAL MEASUREMENT INVARIANCE ANALYSES
Items suitable for administration
Scoring instructions and psychometric information, suitable for hand-scoring

## 48QB6
Items in a recommended format for administration
Scoring instructions and psychometric information, suitable for hand-scoring