---
title: "What We Could Gain From a More Global Psychology"
description: |
  Scientific, moral, and professional reasons to increase inclusion in research
author:
  - name: Amber Gayle Thalmayer
date: 2020-10-19
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Originally posted October 19, 2020 to Psychology Today

People the world over have many similarities:  We all use metaphors, jokes, and insults, we have marriages and kinship rules, and group affiliations. Anthropologist Donald Brown compiled an intriguing list of hundreds of universal aspects of human societies. But we also know that psychological differences across cultures emerge early. Cultural upbringing determines things as basic as where your eyes will move when you look at a painting, and whether you fall prey to certain optical illusions. And even if all societies have marriages, how marriage partners are chosen and what we expect from the experience vary dramatically.

The vast majority of psychological research, however, is conducted on a small subgroup, the 11 percent of us who live in Western, industrialized countries. A recent report by my colleagues and I shows that over 90 percent of recent articles in six top psychology journals drew on such samples (over 60 percent of American). We know a lot about this narrow slice of the human family, but we are neglecting to learn about everyone else.

Studies with White or male samples are less likely to indicate participant characteristics in the title, as compared to those with more women or ethnic minority samples; such persons may still be treated as more “proto-typical” people. This is also true when it comes to the nationality of participants. Article titles speak of psychological phenomena (e.g. “self-esteem”, “language acquisition”, “personality predictors of life outcomes”), without specifying who we are talking about. There has been an unstated and convenient assumption that the college students near at hand in North America and similar societies can stand in for everyone. But this almost certainly isn’t true, and a mono-cultural research base deprives us of observations of psychological diversity and the new insights that might result. 

International research does exist. Our analysis focused on six particularly influential empirical journals, among the most cited in psychology, which function to some extent as “gatekeepers” to their subdomains. There are also hundreds of peer-reviewed journals specific to regions or with the word “international” in their names, whose missions are global.

This research, however, is less likely to reach a broad audience. During a visiting scholar stay at the national university of Malaysia last winter, I gave a workshop on publishing in international journals. Many participants described rejection letters from important journals in their areas, which suggested that their studies would be more relevant to a local journal and questioned whether a Malaysian study would interest an international audience.

I urged my Malaysian colleagues to point out to editors and reviewers that 60 percent of the world’s population lives in Asia, making Malaysia’s multi-ethnic Asian society more globally representative than the United States. Given the Muslim majority, they could also point to the relevance of their work to the 25 percent of the global population who identify as Muslim. There is no objective reason to consider a Malaysian sample less relevant than a Western one, but old habits (and biases) die hard.

Does this lack of representation in science matter? If you live in the United States and don’t plan to work or live abroad, should you care? I would argue: yes and yes. As leading cultural psychologist Fons van de Vijver wrote, there are moral, professional, and intellectual reasons that psychological science should be more international. The moral reasons seem to me the most self-evident. Ignoring most of the world, while supposing that psychology is a general science, echoes imperialist attitudes that modern scientists should make an extra effort to avoid.

Professionally and practically, more representative science means better tools and treatments for people all over the world. This includes the diverse population in the United States. A lot can go wrong when Americans export their ideas about diagnosis and treatment to other countries. Ethan Watters’ Crazy Like Us is a hair-raising but great read about how this can happen despite good intentions. In Namibia, where I’ve been conducting research, mental health needs are significant. There is trauma due to a long war for independence and the widespread HIV/AIDS epidemic. Training for psychologists and social workers relies on American materials and at clinics diagnoses are made with the Diagnostic and Statistical Manual of the American Psychiatric Association. This can lead to incongruities, which professionals are on their own to resolve. For example, a Namibian clinical psychologist told me that eye contact with the client was emphasized in her training in the United States and South Africa. But among some groups in Namibia, direct eye contact is seen as disrespectful and aggressive. While diagnoses such as depression and anxiety may have some worldwide similarities, the specific ways they will be spoken about and suitable ways to treat them can vary in important ways. 

Scientifically and intellectually, we have a lot to gain from better representation in our science. One benefit is new ideas. For example, Dixon Chibanda and his team in Zimbabwe adapted principles of cognitive-behavioral therapy to local needs and resources, in a way that maximizes accessibility and reach and minimizes costs. This may be found useful in many other settings, including in the United States. Another scientific benefit is increased precision and efficiency in science. As we understand cultural differences better, we can make better-targeted hypotheses about where a phenomenon or treatment is likely to work similarly. Understanding group differences can also account for unexplained variance in outcomes.

Finally, more international research can help us define the foreground of culturally specific aspects of psychology against the background of human universals. Among other things, this teaches us about ourselves. If a theory, model, or instrument created in the West also works in places with different social conditions and values, perhaps we’re on to something universal. In the industrialized West, there is a wealth of psychological knowledge, but often we don’t know which of these research findings define the human experience and which define our particular societies.

Making psychology more globally inclusive, however, is easier said than done. It is complex to translate measures to mean the same thing across contexts and to find methods that are analogous but socially and practically workable. For example, while it might be most efficient to collect survey responses online in the United States and Europe, this could lead to biased samples in Africa, among other places, where fewer people have computer access. For this reason, it might make the most sense for a local interviewer to read survey questions aloud.  No single study can answer our questions. It takes a multiplicity of creative approaches, seeking corroboration across sources, and taking time to get the bottom of conflicting findings. In future blog posts, I look forward to sharing examples and some of the challenges and joys of working towards a more globally inclusive science. 


